"""empty message

Revision ID: a1a3db8bbbf9
Revises: e8040589fbad
Create Date: 2020-12-06 12:02:37.184781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a3db8bbbf9'
down_revision = 'e8040589fbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'creator',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'creator',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
